import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "../scss/main.scss";
import PageRender from "./PageRender";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Next Boilerplate",
  description: "Generated by Boilerplate web application",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, interactive-widget=resizes-content"
        />
      </Head>

      <body
        className={`scrollbar overflow-x-hidden antialiased ${inter.className}`}
        suppressHydrationWarning={true}
      >
        <PageRender>{children}</PageRender>
      </body>
    </html>
  );
}
